version: "3"

services:
  chatgpt_web:
    container_name: chatgpt_web
    restart: always
    # depends_on:
    #   - mocked_api
    #   - llama_api
    env_file:
      - .env
    ports:
      - 5173:5173
    volumes:
      - .:/app
    build:
      context: "."
      dockerfile: Dockerfile

  # mocked_api:
  #   container_name: mocked_api
  #   build:
  #       context: "."
  #       dockerfile: mocked_api/Dockerfile-mockapi
  #   restart: always
  #   ports:
  #     - 5174:5174

  # llama_api:
  #   build: ./llama_api/.
  #   ports:
  #     - 5174:8000
  #   env_file:
  #    - .env
  #   volumes:
  #     - ./models/:/models:cached
