FROM python:3-alpine
WORKDIR /work

RUN pip install "fastapi<1.0" "uvicorn<1.0" "lorem-text<4.0"
COPY mocked_api/mock_api.py .
COPY mocked_api/models_response.json .

CMD ["uvicorn", "mock_api:app", "--host", "0.0.0.0", "--port", "5174"]
