name: Update Patch Version

on:
  # Allow manual trigger
  workflow_dispatch:
  # Allow trigger from other workflows
  workflow_call:

jobs:
  update-version:
    name: Update Version
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0 # Will fail to push without this.

      - name: Configure Identity
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Deps
        run: npm ci
      
      - name: Update Version
        run: npm version patch --git-tag-version false
      
      - name: Update Changelog
        run: npm run changelog

      - name: Commit Files
        run: |
          git commit -a -m "Update Version & Changelog"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
      
  create-release:
    name: Create Release
    uses: ./.github/workflows/create-release.yml
    secrets:
      PAT: ${{ secrets.PAT }} # Need this to trigger the build-release action
    needs: 
      - update-version
